export const RECORD_APP_SIDEBAR_COLLAPSE = 'RECORD_APP_SIDEBAR_COLLAPSE'

export const RECORD_AUTH_USER = 'RECORD_AUTH_USER'
export const RECORD_AUTH_PERMISSIONS = 'RECORD_AUTH_PERMISSIONS'
export const RECORD_AUTH_MENUS = 'RECORD_AUTH_MENUS'
